// Wrangler `main` entry (see wrangler.toml). Re-exports the SvelteKit worker
// generated by @sveltejs/adapter-cloudflare and adds the `scheduled` handler
// for the [triggers] cron expressions, dispatching to the /api/cron/*
// endpoints in-process via the generated worker's own fetch export.
//
// This file lives at the repo root, outside tsconfig's `include`, on purpose:
// the generated import below only exists after `pnpm build`, and CI runs
// `pnpm check` without building.
import worker from './.svelte-kit/cloudflare/_worker.js';
import { runScheduledJobs } from './src/lib/server/cron/schedule.ts';
import { createSentryCheckIn } from './src/lib/server/cron/sentry-check-in.ts';

export default {
	...worker,
	/**
	 * @param {ScheduledController} controller
	 * @param {unknown} env
	 * @param {ExecutionContext} ctx
	 */
	async scheduled(controller, env, ctx) {
		await runScheduledJobs(
			controller.cron,
			env,
			(request) => worker.fetch(request, env, ctx),
			createSentryCheckIn(env.SENTRY_ENVIRONMENT)
		);
	}
};
