name = "corvmc"
compatibility_date = "2025-05-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "corvmc-db"
database_id = "e43655a1-10ca-4c03-965c-d0c3bd77c0ae"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "corvmc"

[[kv_namespaces]]
binding = "KV"
id = "fc85459046fe47f9bbfae4f343012041"
