/**
 * Pre-compile the MJML campaign layout into HTML at build time.
 *
 * This avoids bundling the heavy mjml runtime (and its transitive
 * dependency on typescript via cosmiconfig) into the Worker.
 *
 * Run: pnpm tsx scripts/compile-email-layouts.ts
 *
 * NOTE: The transactional (notification) email layout + templates have moved to
 * Postmark-hosted templates (source of truth in postmark/templates, pushed via
 * `pnpm email:push`). See docs/postmark-template-migration.md.
 *
 * TODO: Migrate the marketing campaign layout to a Postmark layout + batch
 * template sending too, then delete this script and the mjml dependency
 * entirely. Tracked in docs/postmark-template-migration.md ("out of scope").
 */
import mjml2html from 'mjml';
import { writeFileSync, mkdirSync } from 'node:fs';

const OUTDIR = 'src/lib/server/generated';

// ---------------------------------------------------------------------------
// Campaign email layout (marketing emails)
// ---------------------------------------------------------------------------
// Uses placeholders: {{PREVIEW_TEXT}}, {{CONTENT}}, {{FOOTER}}

const campaignMjml = `
<mjml>
  <mj-head>
    <mj-preview>{{PREVIEW_TEXT}}</mj-preview>
    <mj-attributes>
      <mj-all font-family="system-ui, -apple-system, 'Segoe UI', sans-serif" />
      <mj-text font-size="15px" line-height="1.6" color="#374151" />
      <mj-button background-color="#6366f1" border-radius="6px" font-size="15px" font-weight="600" />
    </mj-attributes>
    <mj-style>
      .footer-text { font-size: 12px; color: #9ca3af; }
      a { color: #6366f1; }
    </mj-style>
  </mj-head>
  <mj-body background-color="#f3f4f6">
    <mj-section padding="20px 0 0">
      <mj-column>
        <mj-text align="center" font-size="22px" font-weight="700" color="#111827">
          CorvMC
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#ffffff" border-radius="8px" padding="32px 24px">
      <mj-column>
        <mj-text>{{CONTENT}}</mj-text>
      </mj-column>
    </mj-section>

    <mj-section padding="16px 0">
      <mj-column>
        <mj-text align="center" css-class="footer-text">
          {{FOOTER}}
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
`;

async function compile(name: string, mjmlSource: string): Promise<string> {
	const result = await mjml2html(mjmlSource, {
		validationLevel: 'soft',
		minify: false // keep readable; wrangler will minify
	});

	if (result.errors?.length > 0) {
		console.warn(`[compile-email-layouts] ${name} warnings:`, result.errors);
	}

	return result.html;
}

mkdirSync(OUTDIR, { recursive: true });

const campaignHtml = await compile('campaign', campaignMjml);

const header = `// AUTO-GENERATED by scripts/compile-email-layouts.ts — do not edit\n\n`;

writeFileSync(
	`${OUTDIR}/email-layout-campaign.ts`,
	`${header}export const CAMPAIGN_LAYOUT = ${JSON.stringify(campaignHtml)};\n`
);

console.log('✅ Campaign email layout compiled to', OUTDIR);
